name: build-bluepay
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          cache: maven
      - name: Build jar
        run: mvn clean compile jib:build
#      - name: Deploy to test
#        uses: johnbeynon/render-deploy-action@v0.0.8
#        with:
#          service-id: srv-cs2ffge8ii6s739h971g
#          api-key: rnd_OAgy4dIBWs4IjWZlreSPXVkAN6Nc
#          wait-for-success: true